import type { NextPage } from "next"
import Head from "next/head"
import { useState } from "react"
import { Item } from "types"
import { v4 as uuidv4 } from "uuid"

const Home: NextPage = () => {
  const [list, setList] = useState<Item[]>([])
  const [showModal, setShowModal] = useState<boolean>(false)
  const [itemValue, setItemValue] = useState<string>("")

  const addItem = (e: any) => {
    e.preventDefault()
    const id = uuidv4()
    const dataToAdd = {
      name: itemValue,
      id,
    }
    setList([...list, dataToAdd])
    setItemValue("")
    setShowModal(false)
  }

  const deleteItem = (id: string) => {
    const newList = list.filter((item) => item.id !== id)
    setList(newList)
  }

  return (
    <div>
      <Head>
        <title>Market list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Supermarket List</h1>
      </header>
      <section>
        <h2>{list.length} item(s)</h2>
        <ul>
          {list.map((e) => (
            <li key={e.id}>
              <span>{e.name}</span>
              <button onClick={() => deleteItem(e.id)}>delete</button>
            </li>
          ))}
        </ul>
        {showModal ? (
          <article>
            <form onSubmit={addItem}>
              <label>Add Item</label>
              <input
                type="text"
                value={itemValue}
                onChange={(e) => {
                  setItemValue(e.target.value)
                }}
                autoFocus
              />
              <button type="button" onClick={() => setShowModal(false)}>
                close
              </button>
              <button type="submit">add</button>
            </form>
          </article>
        ) : (
          <button onClick={() => setShowModal(true)}>Add item</button>
        )}
      </section>
    </div>
  )
}

export default Home
